/*
 * This file is generated by jOOQ.
 */
package ru.alexredby.stocktaking.model


import kotlin.collections.List

import org.jooq.Schema
import org.jooq.impl.CatalogImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()
    }

    /**
     * The schema <code>stocktaking</code>.
     */
    val STOCKTAKING: Stocktaking get(): Stocktaking = Stocktaking.STOCKTAKING

    override fun getSchemas(): List<Schema> = listOf(
        Stocktaking.STOCKTAKING
    )
}
