/*
 * This file is generated by jOOQ.
 */
package ru.alexredby.stocktaking.model


import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl
import ru.alexredby.stocktaking.model.tables.Item

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DefaultSchema : SchemaImpl(DSL.name(""), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("")) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA: DefaultSchema = DefaultSchema()
    }

    /**
     * The table <code>ITEM</code>.
     */
    val ITEM: Item get() = Item.ITEM

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Item.ITEM
    )
}
