include classpath("database.conf")
include classpath("tarkov-dev.conf")

server {
  host: "0.0.0.0"
  host: ${?APP_HOST}
  port: 8080
  port: ${?APP_PORT}
  # https://ktor.io/docs/server-development-mode.html#enable
  development: false
  development: ${?APP_DEVELOPMENT}
}
