server {
  port: 8080
  # https://ktor.io/docs/server-development-mode.html#enable
  development: true
}

database {
  host: localhost
  host: ${?DB_HOST}
  port: 5432
  name: stocktaking
  user: stocktaking
  password: ${DB_PASSWORD}
  cp {
    maximumPoolSize: 10
    minimumIdle: 2
    connectionTimeout: 10000
    idleTimeout: 600000
    maxLifetime: 1800000
  }
}
