include classpath("database.conf")

server {
  port: 8080
  # https://ktor.io/docs/server-development-mode.html#enable
  development: true
}

tarkovDev {
  endpoint: "https://api.tarkov.dev/graphql"
  endpoint: ${?TARKOV_DEV_ENDPOINT}
  connectTimeoutMillis: 5000
  connectTimeoutMillis: ${?TARKOV_DEV_CONNECT_TIMEOUT_MILLIS}
  readTimeoutMillis: 15000
  readTimeoutMillis: ${?TARKOV_DEV_READ_TIMEOUT_MILLIS}
  retryCount: 2
  retryCount: ${?TARKOV_DEV_RETRY_COUNT}
}
