database {
  host: localhost
  host: ${?DB_HOST}
  port: 5432
  port: ${?DB_PORT}
  name: stocktaking
  name: ${?DB_NAME}
  user: stocktaking
  user: ${?DB_USER}
  password: ${DB_PASSWORD}
  cp {
    maximumPoolSize: 10
    minimumIdle: 2
    connectionTimeout: 10000
    idleTimeout: 600000
    maxLifetime: 1800000
  }
}
