@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package ru.alexredby.stocktaking.model.tables.references


import ru.alexredby.stocktaking.model.tables.Item



/**
 * The table <code>ITEM</code>.
 */
val ITEM: Item = Item.ITEM
